### ISSUE TITLE
API interface to job information

### ISSUE THREAD

**Issue by jacobroufa** [skidvis/Midwest-Dev-Chat#10]
@skidvis can we add an endpoint to access job information, for the purpose of feeding a Slack bot with some data? I initially wanted to use the job opportunities spreadsheet as a data source to feed [jacobroufa/jobbot](https://github.com/jacobroufa/jobbot) but seeing as we're moving to a more user-friendly presentation outside of Slack, it would be nice to have programmatic access to this stuff.

My initial request is for a GET only `api/devs` (or any other appropriately named) endpoint from which to query the largest set of data. Everything else can be done from within the slack bot. Eventually it would be nice to add filters to that, e.g. `api/devs/active` or `api/devs?availability=remote`... sky is the limit really. Initially though, just a list will suffice.

**Comment by skidvis** [comment]
Basic API added for devs and jobs. 

Devs
- `GET` midwestdevchat.com/api/devs
  - lists all users who have they're `availability` to anything other than `Unavailable`

Jobs
- `GET` midwestdevchat.com/api/jobs
  - lists all available jobs
- `GET` midwestdevchat.com/api/jobs?remote_options=Remote%20Only
  - filters jobs by provided `remote_options` url_encoded string
- `GET` midwestdevchat.com/api/jobs?title_like=`{search_query}`
  - filters jobs by matching job titles with the provided search string
- `GET` midwestdevchat.com/api/jobs?description_like=`{search_query}`
  - filters jobs by matching job descriptions with the provided search string
